### ISSUE TITLE
Library Example 

### ISSUE THREAD

**Issue by brandoncole** [google/rejoiner#15]
First of all great stuff here.  The code generation and simplicity based on protobufs is great.  I've been able to successfully run the Hello World and Streaming example.  However I'm having problems getting the Library example to work.  It indicates it's still a work in progress so this might be a known issue.  My steps locally are:

- Run `./build/install/examples/bin/shelf-backend`
- Run `./build/install/examples/bin/book-backend`
- Run `./build/install/examples/bin/library-graphqlserver`
- Go to `http://localhost:8080`

Error:

```
Problem accessing /. Reason:

    Not Found
Powered by Jetty:// 9.3.8.v20160314
```

Admittedly I'm a Go programmer primarily, Java secondarily so there could be something I've done on my side related to configuration or misunderstanding that might be mistaken.

**Comment by siderakis** [comment]
This is broken, I'm fixing it now

**Comment by brandoncole** [comment]
Thanks @siderakis!
