### ISSUE TITLE
DataLoaders?

### ISSUE THREAD

**Issue by ebenoist** [google/rejoiner#19]
Can someone point me to how one would use DataLoaders with this library?

**Comment by siderakis** [comment]
I haven’t used dataloaders with rejoiner yet but it’s in my TODO list.

It should be pretty straight forward besides possibly knowing when to dispatch. We could add some signaling into the framework if necessary.

**Comment by ebenoist** [comment]
Would you inject the DataLoader into the query args like you would a grpc client? I'd be happy to write up an example for docs if you can point me in the right direction (i.e. how you would do it for the library example).

**Comment by siderakis** [comment]
as discussed in #17 the Library example now uses a dataloader for fetching books
