### ISSUE TITLE
0.0.2-SNAPSHOT Availability

### ISSUE THREAD

**Issue by mhamrah** [google/rejoiner#28]
Rejoiner Version 0.0.2-SNAPSHOT is listed here: https://github.com/google/rejoiner/blob/08e03e9de00ae1eb3bd7b540333aced5a69378bd/examples/build.gradle#L36 but is not available via the sonatype snapshots repository here: https://oss.sonatype.org/content/repositories/snapshots/com/google/api/graphql/rejoiner/.

Is there a timeline to make this available?

Thank you,

M

**Comment by siderakis** [comment]
I just deployed, apologies for the delay!
