### ISSUE TITLE
Adding rejoiner as a user to docusaurus.io

### ISSUE THREAD

**Issue by yangshun** [google/rejoiner#29]
Hi there, Docusaurus maintainer here 👋. This is not a real issue per se, just using this way to ask if rejoiner is ok with being showcased on https://docusaurus.io as [a user](https://docusaurus.io/en/users.html)?

We got a PR ready at https://github.com/facebook/Docusaurus/pull/606. 

Hope to get the green light from you!

**Comment by siderakis** [comment]
Sure, that would be great! Thanks!!
