### ISSUE TITLE
release of non-snapshots jars to maven

### ISSUE THREAD

**Issue by entzik** [google/rejoiner#35]
greetings, 

really happy with the functionality and stability in as it is, would it be possible to release a at least a 0.0.1 non-snapshot jar to your maven repo?

is there anything outstanding that is blocking such a release, if so I'd be happy to  help out.

**Comment by siderakis** [comment]
Thanks for the feedback.

Good idea, there is a bit more configuration that’s required for a non-snapshot jar that I need to do. If you see anything in the pom.xml files that are missing feel free to send a PR.

**Comment by siderakis** [comment]
Sorry for the delay, its now released at:

Apache Maven
```
<dependency>
    <groupId>com.google.api.graphql</groupId>
    <artifactId>rejoiner</artifactId>
    <version>0.0.4</version>
</dependency>
```

Gradle/Grails
`compile 'com.google.api.graphql:rejoiner:0.0.4'`

Scala SBT
`libraryDependencies += "com.google.api.graphql" % "rejoiner" % "0.0.4"`
