### ISSUE TITLE
HTTPS for the website?

### ISSUE THREAD

**Issue by shuhei** [google/rejoiner#46]
Hi, I just came across the website and found it with `http://`. The website seems to be using GitHub Pages. How about changing it to `https://`?

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by siderakis** [comment]
Good idea, thanks! I'll give that a try :-)

**Comment by siderakis** [comment]
https is now working and http redirects to https, thanks again!

**Comment by shuhei** [comment]
Wow, that was fast! Thank you!
