### ISSUE TITLE
Inconsistency between input field and output field name conversion

### ISSUE THREAD

**Issue by wangyuesong** [google/rejoiner#47]
We are using rejoiner in production and found that there is an inconsistency between generated  output field's GraphqlFieldDefinition and input field's field GraphqlInputObjectField.
For example, for a message like:
`
message Account {
   string account_p_code = 1
}
`
The input graphql type generated will be
`
Input_qapi_Account {
   account_p_code: string
}
`
The output graphql type generated will be 
`
qapi_Account {
  accountPCode: string
}
` 
This seems to be an inconsistency. 
The logic generating fullName to GraphqlType map is here in [ProtoRegistry.java](https://github.com/google/rejoiner/blob/master/rejoiner/src/main/java/com/google/api/graphql/rejoiner/ProtoRegistry.java#L163-L177)
And it generates input type here in [GqlInputConverter.java](https://github.com/google/rejoiner/blob/master/rejoiner/src/main/java/com/google/api/graphql/rejoiner/GqlInputConverter.java#L95-L98), which lacks camel case conversion

generates output type here in [ProtoToGql.java](https://github.com/google/rejoiner/blob/master/rejoiner/src/main/java/com/google/api/graphql/rejoiner/ProtoToGql.java#L151)

Is this intentional? And i don't see there is a way to configure it.

I can submit a PR with tests to
(1) Fix this inconsistency, but this might break existing user's behavior
(2) Configure this behavior somewhere? I haven't looked carefully and not sure if we already have some machanisms to configure the mapping between protobuf field names and graphql field names.

Let me know if this make sense and if i can help on that :) thanks!

**Comment by siderakis** [comment]
I think consistently using camelcase is best option. 

If someone can’t upgrade because they need underscore case field names we can release an update that’s configurable at that time.
