### ISSUE TITLE
example HelloWorld graphqlserver 404 not found

### ISSUE THREAD

**Issue by bmweller** [google/rejoiner#7]
when following the example README 

getting below on http://localhost:8080/
HTTP ERROR: 404
Problem accessing /. Reason: 
    Not Found

Powered by Jetty:// 9.3.8.v20160314

running the backend successfully
$ ./server.sh
Jan 24, 2018 7:40:42 AM com.google.api.graphql.examples.helloworld.backend.HelloWorldServer start
INFO: Server started, listening on 50051

graphql frontend starts ok as well
$ bazel run examples:helloworld_graphqlserver
...
[main] INFO org.eclipse.jetty.util.log - Logging initialized @192ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.3.8.v20160314
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@4816278d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started @1208ms

$ bazel version
Build label: 0.9.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Dec 19 09:32:04 2017 (1513675924)
Build timestamp: 1513675924
Build timestamp as int: 1513675924

**Comment by siderakis** [comment]
I have seen the same issue when using the newest version of Jetty. I couldn't replicate this; it might be specific to running on Windows. It looks like there might be an issue with loading static resources when using Jetty and Bazel. We are planning to switch the demos to use Maven which might fix this.

In the WORKSPACE file can you try switching the jetty-server version to look like this (lines 119-126):

transitive_maven_jar(
  name = "dependencies",
  artifacts = [
    # "org.eclipse.jetty:jetty-server:9.3.8.v20160314",
    # static resources are not found for newer version
    "org.eclipse.jetty:jetty-server:jar:9.4.8.v20171121",
  ]
)

**Comment by bmweller** [comment]
Thanks for the suggestion, I've given that a try and had the same result.   Is the resource folder meant to be included in the jar file contents?  I noted a change from Dec 17 where BUILD file under the graphqlserver directory specifically dropped that directory as part of the java_binary/data directive and moved into the same directive at the examples directory level...  I'm a bazel novice so this probably isn't related

**Comment by siderakis** [comment]
I setup a gradle build for the helloworld graphqlserver example, if you want to try it here are the steps:

- check out the "gradle" branch 
- cd examples
- ./gradlew installDist
- ./build/install/examples/bin/helloworld-graphqlserver
- visit http://localhost:8080/

**Comment by bmweller** [comment]
Thanks, seems like two maven repo dependacies are unavailable

 ./gradlew installDist
:helloworldGraphqlServer FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':runtime'.
> Could not find com.google.api.graphql:rejoiner:0.0.1-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/google/api/graphql/rejoiner/0.0.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/google/api/graphql/rejoiner/0.0.1-SNAPSHOT/rejoiner-0.0.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/google/api/graphql/rejoiner/0.0.1-SNAPSHOT/rejoiner-0.0.1-SNAPSHOT.jar

  Required by:
      project :
> Could not find com.google.api.graphql:execution:0.0.1-SNAPSHOT.
  Searched in the following locations:
      https://repo1.maven.org/maven2/com/google/api/graphql/execution/0.0.1-SNAPSHOT/maven-metadata.xml
      https://repo1.maven.org/maven2/com/google/api/graphql/execution/0.0.1-SNAPSHOT/execution-0.0.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/com/google/api/graphql/execution/0.0.1-SNAPSHOT/execution-0.0.1-SNAPSHOT.jar
  
  Required by:
      project :

**Comment by siderakis** [comment]
Can you try updating build.gradle to include the snapshots repo.

repositories {
  mavenCentral()
  mavenLocal()
  maven {
    url 'https://oss.sonatype.org/content/repositories/snapshots/'
  }
}

For example the execution jar is here: http://oss.sonatype.org/content/repositories/snapshots/com/google/api/graphql/execution/0.0.1-SNAPSHOT/execution-0.0.1-20180124.221530-1.jar

**Comment by siderakis** [comment]
I've updated the gradle branch and tested it on a second machine. Seems to be working.

**Comment by bmweller** [comment]
Gradle build now successful, however getting slf4j dependency error on startup

 ./build/install/examples/bin/helloworld-graphqlserver
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by siderakis** [comment]
I got those errors too. Were you able to visit http://localhost:8080 ?

**Comment by siderakis** [comment]
Switching to gradle in #11 should fix this issue. I'm closing this issue, please reopen is the issue persists. Thanks!

**Comment by bmweller** [comment]
my apologies, I had assume it was a fatal error having not printed out the localhost:8080 url.  It does work, will close this issue.
