### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by sheepdreamofandroids** [google/rejoiner#74]
Hi, I'm using rejoiner and I'm really impressed with the performance and what I can do with it right now.

Unfortunately there seems to be no progress lately and there are some things that I would like to change. I could simply fork and do whatever I feel like but I would prefer to contribute back here. That is of course, if you're still interested in pursuing this project.

**Comment by siderakis** [comment]
Hey Guss,

I’d be happy to discuss any changes you are thinking about. We have been making minor changes internally and need to sync them to GitHub.

**Comment by sheepdreamofandroids** [comment]
Hey Nick,

I'd like to make the use of guice optional. In essence it is needed to create 5 sets as input for SchemaProviderModule. Removing the need for guice should make it possible to build with quarkus.

Also I'm looking for adding hooks to modify the schema once it's assembled. I'm adding filter and aggregation expressions to every list-type field right now, but I have to copy the whole schema in the process. Not really a problem, just ugly.

I'm working on parsing swagger files to integrate rest endpoints as well. Is that something you would be interested in?

Anyway, it's good to read that this great project is still

**Comment by siderakis** [comment]
I'd like to make the use of guice optional. In essence it is needed to create 5 sets as input for SchemaProviderModule. Removing the need for guice should make it possible to build with quarkus.
Essentially this would mean separating out the Relay related code.

>> I’m open to trying out a refactor to make guice optional, you’re not the first to request that. Would you still want something like the annotated methods in the Schema module?

Also I'm looking for adding hooks to modify the schema once it's assembled. I'm adding filter and aggregation expressions to every list-type field right now, but I have to copy the whole schema in the process. Not really a problem, just ugly.

>> this is something we definitely want to support.

I'm working on parsing swagger files to integrate rest endpoints as well. Is that something you would be interested in?

>> I’m thinking of separating the proto functionality from the “joining” functionality to better support exactly this. The proto functionality will be one of many integrations.

Anyway, it's good to read that this great project is still going strong.

**Comment by sheepdreamofandroids** [comment]
> I’m open to trying out a refactor to make guice optional, you’re not the first to request that. Would you still want something like the annotated methods in the Schema module?

At the moment I'm looking for a way to programmatically add new query's and schemamodifications coming from a rest endpoint. I saw a new commit introducing SchemaBundles which is just what I need. If `SchemaProviderModule.get()` were in a separate method taking a Set of SchemaBundles, that would be great.
Annotated methods are very nice for manually extending the schema but they shouldn't necessarily be on a Module subclass.

**Comment by sheepdreamofandroids** [comment]
Closing this because the project seems alive and well and Schemabundles have landed.
