### ISSUE TITLE
will compile "com.google.api.graphql:rejoiner:0.1.0" change into compile "com.google.api.graphql:rejoiner:0.3.0"

### ISSUE THREAD

**Issue by luziyuan002** [google/rejoiner#85]
new DataLoaderDispatcherInstrumentation() Unable to pass parameters  dataLoaderRegistry，Causes dataLoader to be unusable

**Comment by luziyuan002** [comment]
I hope someone helps me.

**Comment by siderakis** [comment]
I updated the example, thanks for the question. GraphQL-Java updated their API.

https://github.com/google/rejoiner/commit/fcc86b875987d9a422d289c4db77207204278ed9
